/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	docs: {
		"快速入门": [
			"getting-started",
			"quickstart-api-basics",
			"quickstart-rich-styling"
		],
		"高级主题": [
			"advanced-topics-entities",
			"v0-10-api-migration",
			"advanced-topics-decorators",
			"advanced-topics-key-bindings",
			"advanced-topics-managing-focus",
			"advanced-topics-block-styling",
			"advanced-topics-custom-block-render-map",
			"advanced-topics-block-components",
			"advanced-topics-inline-styles",
			"advanced-topics-nested-lists",
			"advanced-topics-text-direction",
			"advanced-topics-editorstate-race-conditions",
			"advanced-topics-issues-and-pitfalls"
		],
		"API参考": [
			"api-reference-editor",
			"api-reference-editor-change-type",
			"api-reference-editor-state",
			"api-reference-content-state",
			"api-reference-content-block",
			"api-reference-character-metadata",
			"api-reference-entity",
			"api-reference-selection-state",
			"api-reference-composite-decorator",
			"api-reference-data-conversion",
			"api-reference-rich-utils",
			"api-reference-atomic-block-utils",
			"api-reference-key-binding-util",
			"api-reference-modifier"
		]
	}
	
	// But you can create a sidebar manually
	/*
	tutorialSidebar: [
		'intro',
		'hello',
		{
			type: 'category',
			label: 'Tutorial',
			items: ['tutorial-basics/create-a-document'],
		},
	],
	 */
};

module.exports = sidebars;
